-- Add missing columns to shops table
ALTER TABLE shops
ADD COLUMN IF NOT EXISTS owner_name TEXT,
ADD COLUMN IF NOT EXISTS alternate_contact TEXT,
ADD COLUMN IF NOT EXISTS email TEXT,
ADD COLUMN IF NOT EXISTS city TEXT,
ADD COLUMN IF NOT EXISTS state TEXT,
ADD COLUMN IF NOT EXISTS pincode TEXT,
ADD COLUMN IF NOT EXISTS gst_number TEXT,
ADD COLUMN IF NOT EXISTS pan_number TEXT,
ADD COLUMN IF NOT EXISTS shop_type TEXT DEFAULT 'retail',
ADD COLUMN IF NOT EXISTS credit_limit TEXT,
ADD COLUMN IF NOT EXISTS payment_terms TEXT DEFAULT 'immediate',
ADD COLUMN IF NOT EXISTS bank_account JSONB,
ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES app_users(id);
